### ISSUE TITLE
bin file - audit or auditjs?

### ISSUE THREAD

**Issue by davidmarkclements** [OSSIndex/auditjs#1]
Hey great tool, I'm looking at mentioning it in the third edition of Node Cookbook (http://www.amazon.co.uk/Node-Cookbook-David-Mark-Clements/dp/1783280433) 

There seems to be a disparity between the readme, and the implementation

Whilst the readme lists the CLI tools name as `audit`, the actual name is `auditjs`, 
the `package.json` file `bin` field would have to be changed to:

```json
  "bin": {
    "audit": "./audit.js"
  },
```

To agree with the Readme. 

However which is the source of truth?

Is the readme going to be changed or is the module going to be updated to agree with readme?

**Comment by OSSIndex** [comment]
Thanks very much for the feedback and the issue report. The README has been updated to reflect the 'auditjs' name.

A new release has been pushed to both GitHub and npm with this change.

**Comment by OSSIndex** [comment]
Needless to say, we would be thrilled if auditjs merits mention in your book.
