### ISSUE TITLE
New angular vulnerability 8398878757 found. The tests need updating.

### ISSUE THREAD

**Issue by qacwnfq** [OSSIndex/auditjs#10]
A new vulnerability was found in angular: 
```
id: 8398878757
Cross Site Scripting (XSS) in JSONP
JSONP allows untrusted resource URLs, which provides a vector for attack by malicious actors.

Affected versions: <1.6.0-rc.0
References:
  * https://github.com/angular/angular.js/commit/6476af83cd0418c84e034a955b12a842794385c4
  * https://github.com/angular/angular.js/issues/11352
  * https://snyk.io/vuln/npm:angular:20150315
```

The tests should be updated to expect it.

Also the JUnit reports report the wrong failure count in the testsuite node, although this doesn't seem to make a difference in Jenkins or anywhere.
While I'm making a PR for the update anyways, I might as well fix it.

**Comment by OSSIndex-Admin** [comment]
Aw heck. I will use this as the driving force behind finally finishing #7, I'll get some mock projects created and available shortly. Sorry :|

**Comment by qacwnfq** [comment]
It's no problem :). Thanks for the quick merge!

**Comment by OSSIndex-Admin** [comment]
And yet more today. I am going to add tests to the database today and will see if I can fix the npm tests. I will let you know if I have troubles.

**Comment by OSSIndex-Admin** [comment]
Updated the current tests in 08fbdae7deaf3b35c9a8d2a6bf99a30ab65414d3

**Comment by OSSIndex-Admin** [comment]
I have a few test projects and am adding some test vulnerabilities. Anything in particular you think should be added? I am adding a variety of things to test:

* Package with no vulnerabilities
* Package with vulnerability in earlier version
* Package with vulnerability in later version
* Package with a vulnerability in
** Exact version
** An  unbounded "downward" range (<2.0.0)
** An unbounded "upward" range (>0.0.0)
** A bounded range (>1.0.0 <=2.0.0)
* Package versions defined in package.json in a variety of Semantic version formats.

**Comment by qacwnfq** [comment]
Sounds good, I can't think of any other cases.

**Comment by OSSIndex-Admin** [comment]
Whoof, I have fallen behind on this. I will finish adding tests this week and update the module.

**Comment by OSSIndex-Admin** [comment]
This will no longer happen. Tests now run against sample projects. I am currently adding more tests for additional coverage. The work is tracked by issue #7
