### ISSUE TITLE
Flag option to ignore packages with no known vulnerabilties

### ISSUE THREAD

**Issue by lahdekorpi** [OSSIndex/auditjs#15]
Having the ability to ignore safe packages would be great.
It's quite annoying to have to scroll through a huge list of unnecessary information.

**Comment by lahdekorpi** [comment]
@OSSIndex-Admin Do you have any plans for something like this?

If you'd like, I can fork this and rewrite the logging part using `winston` for logging the results with different log levels for "No known vulnerabilities...", vulnerabilities and a verbose output of those vulnerabilities.
Or alternatively just the current console.log way but buffering the output in `resultCallback` before showing it (or skip).

**Comment by OSSIndex-Admin** [comment]
That sounds like a good idea, and I am perfectly happy with using `winston`. A pull request would be awesome if you have the time. Things are rather chaotic for me at the moment so it would be a little while before this hits the top of the list. Thanks!

**Comment by lahdekorpi** [comment]
I'll start work in my fork right away.
https://github.com/lahdekorpi/auditjs

**Comment by OSSIndex-Admin** [comment]
I have been very, very distracted in the last few months, but am finally getting back to working on the clients. I was planning on merging your branch and wanted to check that you are happy with the way your code works before I do so.

**Comment by thom-nic** [comment]
Thanks for this, I just started using auditjs and it would be nice to have a mode that only outputs warnings/errors.  I would call it a "less verbose" or "errors only" or "summary" mode: secure packages are not being "ignored" inasmuch as they are just not being printed to stdout.

That said, this is a fantastic tool, it is definitely catching issues that `nsp` missed.

**Comment by OSSIndex-Admin** [comment]
That's great to hear. Thanks! I will definitely look into a less verbose mode as I port the logging work.

**Comment by ken-duck** [comment]
I have implemented basic log levels using Winston for logging. You should get different results when run with:

```
-l error
-l info
-l verbose
--verbose
-q
```

`-l info` is the default and `-q` suppresses all console output.

**Comment by ken-duck** [comment]
@lahdekorpi Note I have not done the modernization that you were doing in your branch. I will look into it and try bringing that over when I get a chance.
