### ISSUE TITLE
Simplify invocation

### ISSUE THREAD

**Issue by ilatypov** [OSSIndex/auditjs#17]
When I run npm install auditjs in my Cygwin terminal, I observe that the ``auditjs.cmd`` file in ``node_modules/.bin`` has ``/bin/sh`` instead of ``node.exe`` and ``node``.

    $ cat node_modules/.bin/auditjs.cmd
    @IF EXIST "%~dp0\/bin/sh.exe" (
      "%~dp0\/bin/sh.exe"  "%~dp0\..\auditjs\audit.js" %*
    ) ELSE (
      @SETLOCAL
      @SET PATHEXT=%PATHEXT:;.JS;=;%
      /bin/sh  "%~dp0\..\auditjs\audit.js" %*
    )

I believe this results in my ``scripts`` entry ``"auditjs": "auditjs -qr && node other-script.js`` to fail,

    $ npm run auditjs
    
    > proj@2.0.0 auditjs C:\cygwin64\home\latypil\proj
    > auditjs -qr && node other-script.js
    
    The system cannot find the path specified.
    
    npm ERR! Windows_NT 6.1.7601
    npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "auditjs"
    npm ERR! node v4.4.3
    npm ERR! npm  v2.15.1
    npm ERR! code ELIFECYCLE
    npm ERR! proj@2.0.0 auditjs: `auditjs -qr && node other-script.js`
    npm ERR! Exit status 1

I found that other npm packages such as nsp work when invoked via a scripts entry.

    $ cat node_modules/.bin/nsp.cmd
    @IF EXIST "%~dp0\node.exe" (
      "%~dp0\node.exe"  "%~dp0\..\nsp\bin\nsp" %*
    ) ELSE (
      @SETLOCAL
      @SET PATHEXT=%PATHEXT:;.JS;=;%
      node  "%~dp0\..\nsp\bin\nsp" %*
    )

I wonder if this can be resolved by changing the way npm is published in npmjs.com?  Perhaps, this issue resulted from a glitch in a version of npm used to publish?

**Comment by OSSIndex-Admin** [comment]
Thanks for the report. I will dig around a bit to see how to best handle the issue and resolve it as soon as possible.

**Comment by OSSIndex-Admin** [comment]
Sorry for the delay, things have been rather chaotic around here lately. I have finally got cygwin installed to try and reproduce the problem.

My first trial was just running the globally installed auditjs from the cygwin terminal, and that seemed to work (this auditjs was installed from the windows console):

```
Gern Blanston@Odin /cygdrive/d/git.vor/auditjs
$ uname -a
CYGWIN_NT-6.3-WOW Odin 2.8.0(0.309/5/3) 2017-04-01 20:42 i686 Cygwin

Gern Blanston@Odin /cygdrive/d/git.vor/auditjs
$ auditjs
[1/304] nodejs v4.6.0   30 known vulnerabilities, 0 affecting installed version
[2/304] step 0.0.6   No known vulnerabilities...
[3/304] colors 1.1.2   No known vulnerabilities...
[4/304] commander 2.9.0   No known vulnerabilities...
[5/304] graceful-readlink 1.0.1   No known vulnerabilities...
[6/304] html-entities 1.2.0   No known vulnerabilities...
[7/304] jsontoxml 0.0.11   No known vulnerabilities...
...
```

I get the same results when running from the command line using a locally installed copy, so that's good.

```
$ ./node_modules/.bin/auditjs
[1/303] nodejs v4.6.0   30 known vulnerabilities, 0 affecting installed version
[2/303] auditjs 2.1.7   No known vulnerabilities...
[3/303] colors 1.1.2   No known vulnerabilities...
...
```

When run from `npm` as suggested in the issue report, I get some different output, but things definitely fail.

```
$ npm run auditjs

> ossindexjs@2.0.0 auditjs D:\git.vor\test
> auditjs -qr

The system cannot find the path specified.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ossindexjs@2.0.0 auditjs: `auditjs -qr`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ossindexjs@2.0.0 auditjs script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Gern Blanston\AppData\Roaming\npm-cache\_logs\2017-06-04T23_38_19_134Z-debug.log
```

More research required. I will try hand editing the auditjs scripts to see if I can get things to work via hacks first.

**Comment by OSSIndex-Admin** [comment]
Making the changes as suggested does fix the issue. Still need to figure out how to generate the correct script.

```
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\..\auditjs\audit.js" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\..\auditjs\audit.js" %*
)
```

**Comment by OSSIndex-Admin** [comment]
So it would appear the issue could be first line of the audit.js script, which reads

```
#!/bin/sh
':' //; exec "$(command -v node || command -v nodejs)" "$0" "$@"
```

As opposed to a commonly expected

```
#!/bin
```

This was done to handle issue https://github.com/OSSIndex/auditjs/issues/12 wherein some installations on some Linux distributions install node in non-standard locations leading to awkward behaviour. I would rather not change the heading in order that I don't break other users to resolve the issue. I will try a few ideas, but think that the simplest solution will be to provide an alternative script to kick things off on windows in situations like this, perhaps called `auditjs-win`

Thoughts?

**Comment by ilatypov** [comment]
So I guess npm parses the first line of the script, removing potential /usr/bin/env, and sticking the rest into the text of the windows batch file it creates when publishing the package.

The two Linux issues under the same number above appear related to (a) leaving CR characters in the shell script and (b) having two installations of NodeJS under names node and nodejs.  I suspect the latter was preferred by Debian to avoid name collision with an older application.

https://github.com/nodejs/node-v0.x-archive/issues/4772

I guess Debian users will have to create a symlink such as ~/bin/node -> /usr/bin/nodejs and prefix their PATH with ${HOME}/bin to resolve the search of the node executable.

**Comment by OSSIndex-Admin** [comment]
You are correct on the Debian front. I think there is even a package to support the symbolic link you mention. What makes it more complex is that in some of our users' installations there are node installations  under both names, one is new and the other is ancient (we're talking v0.10 ancient). The ugly check we do works around that situation. I expect in the not-near but not-far future this problem will likely go away.

Fun :|

**Comment by OSSIndex-Admin** [comment]
Alright, I have added an `auditjs-win` binary/shortcut which should allow things to work on windows again. I will keep looking for a better cross-platform solution for these problems, but at least there is now a workaround.

Thank you for the issue!
