### ISSUE TITLE
Whitelist doesn't seem to work

### ISSUE THREAD

**Issue by ben-moore** [OSSIndex/auditjs#21]
I'm trying to integrate auditjs into our CI build process.  I'm setup a build step to call auditjs specifying a whitelist file as there is a warning I need to suppress for a specific project, however the build process is still failing because auditjs still reports the vulnerability and the process has a non-0 exit code. 

The documentation on what to put in the whitelist file isn't clear, please could you clarify how this should be used to reliably suppress any accepted vulnerabilities?

**Comment by ben-moore** [comment]
Is there anyone able to provide some guidance on this please?

**Comment by OSSIndex-Admin** [comment]
Dang, sorry I did not see this one come in. I will take a look at the issue tonight/tomorrow and see what I can do.

**Comment by OSSIndex-Admin** [comment]
You know what, I think the white list capability is too difficult to use. I will do a quick refactoring to make a simpler version and will send information on it shortly. I expect to have it by the end of the day Monday.

**Comment by OSSIndex-Admin** [comment]
OK. I have added some changes which should make this feature work better. They need a bit more testing, so I have not pushed them to npm yet (that and the machine I do that from needs to be brought back up after some maintenance). I expect I will push the changes out this evening (Monday).

The whitelist has been simplified. You can still do it the original way (which was rather involved), but a much simpler mechanism has been added. The whitelist is now simply a JSON list of vulnerability IDs, where the ID numbers can be seen if you generate a report. The whitelist looks like this:

```
[
8402907551,
8402907552
]
```

From the "XML" reports, which are really JSON embedded within some boilerplate XML, you can find the vulnerability ID quite easily. Here is an example:

```
...
  {
    "id": 8398878757,
    "title": "Cross Site Scripting (XSS) in JSONP",
    "description": "JSONP allows untrusted resource URLs, which provides a vector for attack by malicious actors.",
    "versions": [
      "&lt;1.6.0-rc.0"
    ],
    "references": [
      "https://github.com/angular/angular.js/commit/6476af83cd0418c84e034a955b12a842794385c4",
      "https://github.com/angular/angular.js/issues/11352"
    ],
    "published": 0,
    "updated": 1493261505026
  },
...
```

The vulnerability is right up on top.

Sorry again for the delay. I will be pushing a new version to npm tonight. Please do not hesitate to write if there are more issues and I will try to get to them as quickly as possible. I have a few features on my list that I am hoping to his soon (this week?) on the npm client already.

**Comment by qacwnfq** [comment]
Nice work!

I'd like to add that the reason the whitelist looked so complicated before, was that it was also a documentation, where you could just from the whitelist get an understanding of the details of all whitelisted packages. Maybe this was too verbose, though.

Maybe we should set up a boilerplate example project showing auditjs usage for future reference.

**Comment by ben-moore** [comment]
@OSSIndex-Admin thanks for the update, looks a lot more simple to use.  I've tested locally with the latest version and it seems fine, will validate on the build server once the new version in on NPM.

**Comment by OSSIndex-Admin** [comment]
@qacwnfq I definitely understand, and plan on leaving both methods active. I particularly like the way you specify the project, and then the filtered vulnerabilities within. I will update the readme to explain the usage of the whitelist and will let you know when that is done so you can make sure I have explained things well.

**Comment by OSSIndex-Admin** [comment]
@qacwnfq So you know, the update to the whitelist moved the "filtering" higher up the call tree. This has the effect of hiding the vulnerabilities from the non-report output as well (for both the verbose and simplified whitelisting mechanisms). If this will negatively affect your usage please do let me know.

**Comment by OSSIndex-Admin** [comment]
A new version has now been pushed to npm. I am going to close this issue, but will re-open it if there is any problem.

The [README](https://github.com/OSSIndex/auditjs/blob/master/README.md) has documentation explaining the usage of the whitelist (both the simplified and verbose versions). As mentioned by Fredrik, 
the verbose whitelist is quite useful in documenting the actual vulnerabilities that have been hidden, whereas the simplified version gives you only ID numbers which don't have a heck of a lot of meaning themselves.

@qacwnfq I updated the README to explain how to use the "verbose" whitelist (as well as the simplified whitelist). Any feedback you have on the description would be greatly appreciated.
