### ISSUE TITLE
flag to only report issues

### ISSUE THREAD

**Issue by chadbr** [OSSIndex/auditjs#24]
could we have a flag to only report packages with issues?

**Comment by OSSIndex-Admin** [comment]
Definitely. I will work on it now. I would say I will have a solution soon, and will endeavour to do so. I have a lot of irons in the fire so will apologize in advance if a fix is delayed.

**Comment by chadbr** [comment]
Anything I can do to help?

**Comment by OSSIndex-Admin** [comment]
Thank you for the offer. I am always open to pull requests, but I expect to have this done by the end of this coming weekend at the latest anyhow so it is all good :)

If I cannot reproduce your other issue I might require additional help. I will be able to get back that one later in the week, so we shall see there. I will keep you updated.

**Comment by OSSIndex-Admin** [comment]
Holy smokes. I went and implemented a feature for this, then realized that it already exists. It was added when we put in support for "winston" (a logging framework). You can change the verbosity of the log. Set the logging level to error in this way:

```
auditjs -l error
```

Sorry it took so long to get back to you on this. I noticed that it still prints out a line of dashes when there are no errors. I am fixing that.

**Comment by OSSIndex-Admin** [comment]
Ah, but the error logging appears to have a bug. Fixing that now...

**Comment by OSSIndex-Admin** [comment]
Nope. Testing problem. Everything seems to be running fine. Please let me know if your version does not run properly with the raised logging level.
