### ISSUE TITLE
npm installation fails when using node 8.x and npm 5.x

### ISSUE THREAD

**Issue by jnoksoko** [OSSIndex/auditjs#29]
Getting the same dezalgo error as described in this issue: https://github.com/npm/npm/issues/17444

This issue could be fixed be either updating module's npm dependency to a newer one, or adding support for multiple versions for npm dependency in package.json.

**Comment by OSSIndex-Admin** [comment]
I upgraded npm to 5.6.0

The auditjs version with the fix is 2.3.2

Thanks for the report and help!

**Comment by jnoksoko** [comment]
No problem! And thanks for a great package and making changes so quickly!
