### ISSUE TITLE
Summarize in a text file like license:aggregate-add-third-party (and the OSSIndex maven plugin)

### ISSUE THREAD

**Issue by clausfod** [OSSIndex/auditjs#4]
Hi,

We would very much like to have the same functionality as you implemented in this https://github.com/OSSIndex/ossindex-maven-plugin/issues/4 for the OSSIndex Maven plugin.

Kind regards
Claus Nielsen

**Comment by OSSIndex** [comment]
I am definitely interested. I am checking into merging https://github.com/qacwnfq/auditjs back into my fork, as it seems they have already implemented Jenkins reports in some manner (as well as extended the functionality to support the Bower API as well).

**Comment by OSSIndex** [comment]
Sorry for the delay, I have merged [Fredrik J](https://github.com/qacwnfq)'s updates into the repository, which gives us:

* Bower support
* JUnit reports
* Whitelisting

If you run auditjs while including the `--report` option, a report directory is created with a JUnit format result file which should be suitable for Jenkins use.

**Comment by OSSIndex** [comment]
ps. If you prefer this JUnit format, I can update the maven plugin to do provide this style of output as well without too much problem.

**Comment by clausfod** [comment]
Thanks a lot :+1:
