### ISSUE TITLE
Question: What does x known vulnerabilities, x affecting installed version mean?

### ISSUE THREAD

**Issue by quentinkhoo** [OSSIndex/auditjs#48]
Hello,

I would like to ask, currently I'm using auditjs to scan a web application project for potential vulnerabilities. I noticed that for each dependency, it's either reported as "No known vulnerabilities" or the above. My question is actually how do I interpret the results?

Thank you very much, I hope to hear from you soon.

**Comment by ken-duck** [comment]
Hi. FYI, this text will be changing soon as the new OSS Index API we are moving to provides slightly different data, as well as the fact that the messages are confusing (as you have indicated).

"**X Known Vulnerabilities**": This means that the package has known vulnerabilities across ALL versions, but not necessarily in the version that is currently in use. You can basically ignore this message, and it will not remain when the new version comes out.

"**X affecting installed version**": These are the number of vulnerabilities identified as actually affecting the version of the library that you have installed.

"**No known vulnerabilities**": This indicates that OSS Index has no vulnerabilities against any version of the package. This too will be going away in the next version.

I hope this helps. I expect the new version (3.0.x) will be made properly public shortly. It is definitely worth moving to as it provides access to a much larger database of vulnerabilities. This new database is also the one which will be actively maintained.
