### ISSUE TITLE
Feature Request: Bower support, quiet mode and J-Unit reports and white listing

### ISSUE THREAD

**Issue by qacwnfq** [OSSIndex/auditjs#5]
All these features would be nice for a CI environment like Jenkins. White listing is necessary to achieve stable builds when a vulnerability isn't relevant in the context of an app.

**Comment by OSSIndex** [comment]
Thanks for the very comprehensive PR! I am checking it out now and should merge it within a day or two.

**Comment by OSSIndex** [comment]
Merged, tagged, and uploaded to npm.

**Comment by OSSIndex** [comment]
(ps. Thanks!)
