### ISSUE TITLE
Audit stops with [891/1129] 

### ISSUE THREAD

**Issue by DanielRuf** [OSSIndex/auditjs#50]
It is not clear why the audit does not step at [1129/1129] but stops at [891/1129].

```
[891/1129] yargs-parser 7.0.0   

Installed version: 7.0.0
No known vulnerabilities against package/version...
------------------------------------------------------------


Audited dependencies: 891, Vulnerable: 0, Ignored: 0
✨  Done in 8.88s.
```

**Comment by ken-duck** [comment]
This is most likely caused by the "400" error from this issue: https://github.com/OSSIndex/auditjs/issues/49

Fingers crossed, fixing one fixes the other.

**Comment by ken-duck** [comment]
Published a fix: Version 3.0.6

**Comment by DanielRuf** [comment]
Works now 👍 🎉

**Comment by DanielRuf** [comment]
Thanks for the lightning fast reaction and help and thanks for maintaining auditjs.
