### ISSUE TITLE
feature request: option to set cacheUntil

### ISSUE THREAD

**Issue by DanielRuf** [OSSIndex/auditjs#56]
Currently `cacheUntil` is updated after a while and I found no option to set how long it should be cached.

Also there is no real change in the file.
```diff
-{"cacheUntil":1533974782757,"data":{"coordinates":"npm:yallist@3.0.2","description":"Yet Another Linked List","reference":"https://ossindex.sonatype.org/component/npm:yallist@3.0.2","vulnerabilities":[],"version":"3.0.2","name":"yallist","format":"npm","depPaths":["yallist@3.0.2"]}}
\ No newline at end of file
+{"cacheUntil":1534253797045,"data":{"coordinates":"npm:yallist@3.0.2","description":"Yet Another Linked List","reference":"https://ossindex.sonatype.org/component/npm:yallist@3.0.2","vulnerabilities":[],"version":"3.0.2","name":"yallist","format":"npm","depPaths":["yallist@3.0.2"]}}

**Comment by ken-duck** [comment]
I should be able to fit some time in this week for auditjs fixes and improvements. In particular Thursday is looking quite good. I will try and resolve as many of your issues as possible by the end of the week.

Thanks very much for the suggestions and issue reports!

**Comment by ken-duck** [comment]
The file will only change if new vulnerabilities are found on the server side, or the data for a particular version has changed (new description, for example).  The purpose of the file is to reduce the load on the server, as vulnerabilities are updated once a day at the most, and connections are rate limited so hitting the server many times for the same data wastes the limit and bandwidth.

I can certainly make the cache time adjustable, as there are surely use cases where a longer (or shorter) cache time might be desired.

**Comment by ken-duck** [comment]
You can now specify the cache timeout using either a command line option:
```
--cacheTimeout 256
```

or a config file option:

```
{
  "cache": {
    "timeout": 256
  },
```

In either case the value is the number of hours the cache is valid for. Default is 24 hours.

**Comment by DanielRuf** [comment]
Awesome, I'll test it tomorrow.

Do we have to update the readme / docs and help command?

**Comment by DanielRuf** [comment]
Awesome, I'll test it tomorrow.
I guess we have to mention this in the docs too probably.
