### ISSUE TITLE
Does not work with GitHub URLs

### ISSUE THREAD

**Issue by DanielRuf** [OSSIndex/auditjs#57]
`ENOENT: no such file or directory, open '/Users/druf/.auditjs/cache/auditjs3x/npm:file-cookie-store@github:msikma/file-cookie-store.json'`

package.json:

```
  "dependencies": {
    "argparse": "^1.0.10",
    "babel-polyfill": "^6.1.0",
    "chalk": "^2.3.1",
    "cheerio": "^1.0.0-rc.2",
    "cli-table3": "^0.5.0",
    "mkdirp": "^0.5.1",
    "request": "^2.85.0",
    "requestAsBrowser": "msikma/requestAsBrowser",
    "sanitize-filename": "^1.6.1"
  }
```

**Comment by ken-duck** [comment]
There have been several issues reported in the last couple of days due to not handling similar situations (problems in properly parsing the dependency names/versions). I will endeavour to resolve these today and/or tomorrow.

**Comment by ken-duck** [comment]
I am working on resolving this now. This will be a two stage fix.

The first will just ignore GitHub URLs.

At some point in the (hopefully not too far) future we will be supporting reporting vulnerabilities in GitHub dependencies. This requires server side updates. It is in the roadmap, but won't be really soon, thus the first "fix".

**Comment by DanielRuf** [comment]
Understood, sounds good :+1:
