### ISSUE TITLE
Internal library dependency causes all kinds of CVEs to be reported related to old angularjs dependency

### ISSUE THREAD

**Issue by ggraat** [OSSIndex/auditjs#59]
We are using auditjs version 3.0.8 to check our dependencies. We have the following entry in our package.json:

`"dependencies": { ... "@blueriq/angular": "^0.4.0-alpha.6", ...`

This is a library that we develop internally.

When I run the following command:
`yarn auditjs-win --report --prod`

10 CVEs are reported on this dependency. If I review them, it seems that the @blueriq/angular dependency is recognized as an old angularjs dependency.

Can it be that the scope (@blueriq) is ignored?

**Comment by ken-duck** [comment]
That is almost certainly the case. I will explore what we can do to avoid these problems. There is some server-side work that will be required to truly solve the issue, but I can at least get the client from reporting these invalid issues.
