### ISSUE TITLE
etag package can not be found

### ISSUE THREAD

**Issue by DanielRuf** [OSSIndex/auditjs#65]
`Could not find package matching pkg:npm/ETag@1.8.1`

```
"etag": {
      "version": "1.8.1",
      "resolved": "https://registry.npmjs.org/etag/-/etag-1.8.1.tgz",
      "integrity": "sha1-Qa4u62XvpiJorr/qg6x9eSmbCIc=",
      "dev": true
    },
```

```
{
  "name": "prerender-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "prerender": "^5.3.1"
  }
}

```

**Comment by DanielRuf** [comment]
And also in another project:

`Could not find package matching pkg:npm/jQuery@2.2.0`

**Comment by ken-duck** [comment]
Very odd. I'll work on this one first...

**Comment by ken-duck** [comment]
They definitely work from the website, which would seem to indicate it is an auditjs client side problem.

* https://ossindex.sonatype.org/component/pkg:npm/jQuery@2.2.0
* https://ossindex.sonatype.org/component/pkg:npm/ETag@1.8.1

**Comment by ken-duck** [comment]
I was able to reproduce the ETag issue

```
[49/69] cookie-signature 1.0.6   No known vulnerabilities against package/version...
[50/69] encodeurl 1.0.2   No known vulnerabilities against package/version...
[51/69] escape-html 1.0.3   No known vulnerabilities against package/version...
Could not find package matching pkg:npm/ETag@1.8.1
[52/69] finalhandler 1.1.1   No known vulnerabilities against package/version...
[53/69] parseurl 1.3.2   No known vulnerabilities against package/version...
[54/69] statuses 1.4.0   No known vulnerabilities against package/version...
```

**Comment by ken-duck** [comment]
I believe that it will, yes. There are a few issues throughout the various toolsets on how to handle mixed-case packages. NuGet, for example, is explicitly case sensitive, while others are explicitly case insensitive and still others do not specify. We are gradually learning the ins and outs of each system and adjusting accordingly.
