### ISSUE TITLE
auditjs vs npm audit vs yarn audit

### ISSUE THREAD

**Issue by joh-klein** [OSSIndex/auditjs#73]
How much does the output from these three tools differ? Why use one above the other? I would really appreciate an answer to this!

**Comment by ken-duck** [comment]
I can mostly on speak in hypotheticals, not having complete information on `npm audit` and `yarn audit`.

The major difference is that OSS Index owns and maintains its own vulnerability database that is separate and distinct from that maintained by npmjs. I cannot comment on where npmjs gets its data, but OSS Index has a research team that are constantly looking for new vulnerabilities to add to its database (which supports not only npm but a wide variety of other languages/ecosystems). Based on some limited research, it seems that `yarn audit` uses the same backend as `npm audit` which would likely indicate it is drawing from the same database.

My bias would be obvious if I were to say "oh, use OSS Index it is far superior" ;). It is possible (in fact, likely) that OSS Index's database contains vulnerabilities not known by `npm audit`, and perhaps vice versa as well. For optimal coverage it may be a good idea to use both.

I am not aware of all of the features of the built in `npm audit`. Audit.js does provide reporting capabilities that make it work with Jenkins (JUnit report output formats). It also supports bower, and provides mechanism's for ignoring vulnerability reports from a variety of means. We are quite open to suggestions for features that might make audit.js work better. We are also quite keen on receiving feedback on our data and how that could be improved as well!

OSS Index provides an API to their vulnerability database that makes it possible for you to use it in your own tools and applications (for any ecosystem OSS Index supports).

If you have further questions or suggestions that may help further, please do not hesitate to ask!

**Comment by ken-duck** [comment]
Closing for now, but please do reopen if you have more questions or feedback!

**Comment by KevinFauth** [comment]
Hello! I'm trying to figure out why AuditJS isn't returning any known vulnerabilities on npm packages.

I'm looking at `subtext` package from npm.

https://www.npmjs.com/advisories/1168/versions

https://ossindex.sonatype.org/component/pkg:npm/subtext@6.0.12

I can't seem to find any packages that are reported as vulnerable in npm in ossindex. What am I missing?

**Comment by ken-duck** [comment]
Hmm. Two thoughts:

1. The database has well into the thousands of vulnerabilities against npm

**Comment by ken-duck** [comment]
Yup, a bug caused our processing pipeline to get backed up. This affected a portion of our research - we have several research streams. I will fix the problem, but it might take a little time for the missed vulnerabilities to make it through the research queue. We will be expediting the stalled out streams, though, so I hope to see the data in before the end of the week.

Thanks very much for letting us know!

Thanks for the notification.

**Comment by KevinFauth** [comment]
Awesome - I appreciate the quick response
