### ISSUE TITLE
AuditJS reports wrong vulnerability in Express module

### ISSUE THREAD

**Issue by Yohanna** [OSSIndex/auditjs#75]
I recently started receiving this warning for the Express module

```
express 4.17.1  [VULNERABLE]   1 known vulnerabilities affecting installed version

CWE-22: Improper Limitation of a Pathname to a Restricted Directory ('Path Traversal')
The software uses external input to construct a pathname that is intended to identify a file or directory that is located underneath a restricted parent directory, but the software does not properly neutralize special elements within the pathname that can cause the pathname to resolve to a location that is outside of the restricted directory.

ID: e1f470a8-5800-4828-bad8-a6f001221b16
Details: https://ossindex.sonatype.org/vuln/e1f470a8-5800-4828-bad8-a6f001221b16
Dependency path: /express
```

However, the OSS Index page links to this NPM advisory: https://www.npmjs.com/advisories/453
Which is completely unrelated to the Express module.

I opened an issue in the Express repo as I originally though it's a genuine problem in the module, but it turns out it is not: https://github.com/expressjs/express/issues/3978

**Comment by ken-duck** [comment]
Sorry about that. An interesting confluence of issues came together at the same time to cause this problem. Long story short a number of packages were incorrectly implicated by that vulnerability. You should find it no longer being reported. We are adding in preventative measures so this issue does not reoccur.

Thanks for letting us know!
