### ISSUE TITLE
Bug: JUnit reports report vulnerabilities that have been already fixed

### ISSUE THREAD

**Issue by qacwnfq** [OSSIndex/auditjs#8]
At the moment the JUnit reports report false positives.
E.g. if you audit angular@1.4.3 the reports shouldn't tell you that there is a vulnerability up to version 1.3.
This could create some confusion and lead to unmaintainable whitelists in CI.

**Comment by OSSIndex-Admin** [comment]
I am working on this issue today and will endeavour to have this fixed as soon as possible.

**Comment by qacwnfq** [comment]
Actually it was my bad. I used pkg[vulnerabilities] instead of myVulnerabilities when writing to  the JUnit variable. It is fixed in the pull request.

**Comment by OSSIndex-Admin** [comment]
Heavy. I did not see the pull request come in, sorry. Merged now -- I will do a bit more testing then publish to npm. Thanks!

**Comment by OSSIndex-Admin** [comment]
Fixed by #9
