### ISSUE TITLE
Unable to check packages specified by GitHub path in bower.json

### ISSUE THREAD

**Issue by lifenstein** [OSSIndex/auditjs#80]
A specification in bower.json like `"polymer": "Polymer/polymer#^3.3.0"` results in the error "Warning: Unsupported version for 'polymer'". If I remove everything except the version number, it is correctly processed.

**Comment by ken-duck** [comment]
Hmm. Curious. I will test drive this today.

**Comment by ken-duck** [comment]
Could you give me a small bower.json specification with this dependency inside it. I would like to see the exact way it is represented, cause I have never seen that before. Is it something like this?:

```
{
  "name": "example-app",
...
  "dependencies": {
    "normalize-css": "~2.1.2",
    "polymer": "Polymer/polymer#^3.3.0"
  },
...
}

```

**Comment by lifenstein** [comment]
The first one results in 
> Warning: Unsupported version for 'polymer'

while the second one gives
> polymer 3.3.0   No known vulnerabilities against package/version...

`Polymer/polymer` is essentially `<organisation>/<repo>` - it's the GitHub repo that has the code for the package. This means that it doesn't have to be on the NPM registry, although in this case it is.

It is useful to ensure you're pointing at what you think you're pointing to, in case the registry's package name gets reused by something else later on, and a legacy app starts failing builds.

It's also useful to put in forks of NPM packages. For example, if there's a patch that hasn't been accepted into the package in npm registry, devs can temporarily point to a fork and the app will be none the wiser.

**Comment by lifenstein** [comment]
To answer your question directly @ken-duck, it is the former.

**Comment by lifenstein** [comment]
Oh and it seems the issue is not just with monorepos, which the Polymer one is. This will also reproduce the issue:

```
"dependencies": {
    "auditjs": "OSSIndex/auditjs#^3.2.2"
}
```

**Comment by ken-duck** [comment]
Ya, auditjs does not currently support that format, but it should be pretty easy to do. We can report vulnerabilities against repositories which do not necessarily need packages, auditjs just doesn't know about it.

I'll try and add support in this week.

**Comment by ken-duck** [comment]
Things have been a bit crazy lately, including a bunch of PTO, but I should be able to take a whack at this one tomorrow.

**Comment by ken-duck** [comment]
Try out the new release. It should work, so long as semantic versions are used in relation to the github repositories. We cannot work against arbitrary tags, named branches, or master at this time.

**Comment by lifenstein** [comment]
Thanks Ken, it's not erroring anymore for the specification format in my examples above.

In our usecase, we are actually pointing to the master branches of a bunch of dependencies that we manage ourselves. This lets us update the dependencies and deploy the dependent apps by re-running the deployment scripts, without having to worry about updating 20 different packages one by one with version bumps. It would be great if you could add support for default branches (which may not always be `master` in our case), but I can find workarounds for now.

**Comment by ken-duck** [comment]
That's great to hear. Getting OSS Index to work against branches will be a significantly harder problem. We are thinking about ways to do that, but I suspect it will be rather a longer time coming. There are significant hurdles, alas.
